### ISSUE TITLE
Map DNSSD errors to the library error types

### ISSUE THREAD

**Issue by gmilos** [apple/swift-async-dns-resolver#36]
I'm using the library to query `A` records for a domain where that validly times out. I'm running on macOS, therefore the the call is handled through `DNSSDDNSResolver.queryA`.

I get the following error:

```
other [-65568]:
```

This maps to: https://developer.apple.com/documentation/dnssd/1823426-anonymous/kdnsserviceerr_timeout, this should be translated to [`AsyncDNSResolver.Error.timeout`](https://github.com/apple/swift-async-dns-resolver/blob/08c07ff31a745ee5e522ac10132fb4949834d925/Sources/AsyncDNSResolver/Errors.swift#L43).

More generally, the different error types DNSSD provides should be mapped too: https://developer.apple.com/documentation/dnssd/1823426-anonymous

This is already [being done for Ares](https://github.com/apple/swift-async-dns-resolver/blob/08c07ff31a745ee5e522ac10132fb4949834d925/Sources/AsyncDNSResolver/c-ares/Errors_c-ares.swift).

**Comment by glbrntt** [comment]
What version are you using @gmilos? I think this was fixed in 0.3.0

**Comment by gmilos** [comment]
We are on 0.3.1, the problem is still present there. Looking a bit deeper.

**Comment by gmilos** [comment]
Looks like you resolved it here: https://github.com/apple/swift-async-dns-resolver/pull/27, but it's not tagged. Can you generate one for us?

**Comment by glbrntt** [comment]
Ah, you're right, I mixed it up with #24. I just tagged [0.4.0](https://github.com/apple/swift-async-dns-resolver/releases/tag/0.4.0).
